name: Get AAPT2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) ติดตั้ง build-tools เพื่อดึง aapt2 binary
      - name: Install build-tools
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-34" \
            "build-tools;34.0.0"

      - name: Copy aapt2 binary
        run: |
          mkdir -p aapt2-bin
          cp $ANDROID_HOME/build-tools/34.0.0/aapt2 aapt2-bin/
          chmod +x aapt2-bin/aapt2
          ./aapt2-bin/aapt2 version

      # 2) ดาวน์โหลด aapt2.jar จาก Maven เพื่อตัว libaapt2.so
      - name: Download aapt2.jar
        run: |
          VERSION=8.4.1-10008404   # เวอร์ชันล่าสุดของ aapt2 บน Maven
          echo "Downloading AAPT2 version $VERSION"
          curl -L -o aapt2.jar \
            https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/$VERSION/aapt2-$VERSION-linux.jar

      - name: Extract libaapt2.so
        run: |
          mkdir -p aapt2-lib
          unzip -j aapt2.jar '*/libaapt2.so' -d aapt2-lib
          ls -lh aapt2-lib

      # 3) อัปโหลดทั้ง aapt2 binary และ libaapt2.so
      - name: Upload AAPT2 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aapt2-binaries
          path: |
            aapt2-bin/aapt2
            aapt2-lib/libaapt2.so
