name: Get AAPT2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ดาวน์โหลด aapt2.jar จาก Google Maven
      - name: Download aapt2.jar
        run: |
          VERSION=8.4.1-10008404   # <--- เลือกเวอร์ชันที่ต้องการ
          echo "Downloading AAPT2 version $VERSION"
          curl -L -o aapt2.jar \
            https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/$VERSION/aapt2-$VERSION-linux.jar
          echo "Downloaded aapt2.jar"

      # แตก aapt2 binary และ libaapt2.so
      - name: Extract AAPT2 files
        run: |
          mkdir -p aapt2-bin aapt2-lib
          unzip -j aapt2.jar '*/aapt2' -d aapt2-bin
          unzip -j aapt2.jar '*/libaapt2.so' -d aapt2-lib
          chmod +x aapt2-bin/aapt2
          echo "Extracted files:"
          ls -lh aapt2-bin aapt2-lib

      # ตรวจสอบเวอร์ชัน aapt2 (ทดสอบว่า binary ใช้งานได้)
      - name: Check aapt2 version
        run: |
          ./aapt2-bin/aapt2 version || true

      # อัปโหลดออกมาเป็น Artifact
      - name: Upload AAPT2 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aapt2-binaries
          path: |
            aapt2-bin/aapt2
            aapt2-lib/libaapt2.so
