jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          cmake: 3.22.1

      - name: Find aapt2
        run: |
          echo "Searching aapt2..."
          find $ANDROID_HOME/build-tools -name "aapt2*"
