name: Android AAPT2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ติดตั้ง Android SDK + build-tools
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0

      - name: Find aapt2 binary
        run: |
          echo "Searching aapt2 binary..."
          find $ANDROID_HOME/build-tools -name "aapt2*" || true
          cp $ANDROID_HOME/build-tools/34.0.0/aapt2 ./aapt2

      # ดาวน์โหลด aapt2.jar จาก Google Maven
      - name: Download aapt2.jar
        run: |
          VERSION=8.4.1-10008404   # <-- เวอร์ชันล่าสุดดูจาก Maven ได้
          curl -L -o aapt2.jar \
            https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/$VERSION/aapt2-$VERSION-linux.jar
          echo "Downloaded aapt2.jar"

      # แตกไฟล์ libaapt2.so ออกมา
      - name: Extract libaapt2.so
        run: |
          mkdir -p aapt2-lib
          unzip -j aapt2.jar '*/libaapt2.so' -d aapt2-lib
          ls -lh aapt2-lib

      # อัปโหลดเป็น artifact
      - name: Upload aapt2 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aapt2-binaries
          path: |
            ./aapt2
            ./aapt2-lib/libaapt2.so
